server:
  forward-headers-strategy: framework

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: true # 중요! JPA 테이블 생성 후 data.sql 실행
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always # 항상 실행 (embedded, always, never)
      encoding: UTF-8

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: '{baseUrl}/login/oauth2/code/kakao'
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Kakao
            scope:
              - profile_nickname
              - profile_image
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    display-operation-id: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

jwt:
  secret: ${JWT_SECRET_KEY}
  expiration: 3600000

app:
  api:
    server-url: "https://api-dev.pliview.kr"
  auth:
    host: https://localhost:5173
    redirect-uri: https://localhost:5173/auth/kakao/callback
    secure-cookie: false
    samesite-cookie: Lax
  cors:
    allowed-origins: "https://pliview.kr,https://api-dev.pliview.kr,http://api-dev.pliview.kr,http://localhost:8080,http://localhost:3000,http://localhost:5173,http://127.0.0.1:8080"

logging:
  level:
    org.springframework.security: DEBUG

spotify:
  client-id: ${SPOTIFY_CLIENT_ID}
  client-secret: ${SPOTIFY_CLIENT_SECRET}

client:
  connection-timeout: 5
  read-timeout: 10
